<a href="https://colab.research.google.com/github/raazshrestha9876/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing numpy
import numpy as np

In [ ]:
#creating Array #1D
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [ ]:
#creating Array #2D
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]


In [ ]:
#creating Array #3D
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 9]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]


In [ ]:
#creating a simple array for demonstrating properties
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[4, 5, 6], [8, 9, 10]])
print(arr1)
print(arr2)

#dimensions
print(arr1.ndim)
print(arr2.ndim)

#shape
print(arr1.shape)
print(arr2.shape)

#size
print(arr1.size)
print(arr2.size)

#dtype
print(arr1.dtype)
print(arr2.dtype)

[1 2 3 4 5]
[[ 4  5  6]
 [ 8  9 10]]
1
2
(5,)
(2, 3)
5
6
int64
int64


In [ ]:
#array creation methods

#printing zero value in array
zeros = np.zeros((2, 3))
print(zeros)

#printing one value in array
ones = np.ones((2, 2))
print(ones)

#printing any number value in array
full = np.full((2, 2), 10)
print(full)

#creating an indentity matrix
eye = np.eye(3)
print(eye)

#creating an digonal matrix
diag = np.diag([1, 2, 3])
print(diag)

#range value in array
arange_arr = np.arange(0, 10, 2)
print(arange_arr)

#equally space values
lin_arr = np.linspace(0, 10, 5)
print(lin_arr)




[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[10 10]
 [10 10]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#reshaping and transposing
arr = np.array([[1, 2], [3, 4], [5, 6]])

#reshaping the array to 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

#flatten array into a single 1D array
flattened_arr = arr.flatten()
print(flattened_arr)

#transposing the array
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 3 5]
 [2 4 6]]


In [ ]:
#arithematic & statistical operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

#element-wise addition
print("\nAdd", x + y)

#element-wise subtraction
print("\nSubtract", x - y)

#element-wise multiplication
print("\nMultiply", x * y)

#element-wise division
print("\nDivide", x / y)

#square each element
print("\nSquare", x ** 2)

#square root of each element in y
print("\nSquare Root", np.sqrt(y))

# total sum of array elements
print("\nSum:", np.sum(x))

#average of elements
print("\nAverage:", np.mean(x))

#minimum value
print("\nMinimum:", np.min(x))

#maximum value
print("\nMaximum:", np.max(x))

#standard deviation
print("\nStandard Deviation:", np.std(x))

#cumulative sum
print("\nCumulative Sum:", np.cumsum(x))


Add [5 7 9]

Subtract [-3 -3 -3]

Multiply [ 4 10 18]

Divide [0.25 0.4  0.5 ]

Square [1 4 9]

Square Root [2.         2.23606798 2.44948974]

Sum: 6

Average: 2.0

Minimum: 1

Maximum: 3

Standard Deviation: 0.816496580927726

Cumulative Sum: [1 3 6]


In [ ]:
#advanced methods
data = np.array([3, 1, 2, 2, 5])

#return sorted unique values
print("\nUnquie: ", np.unique(data))

#sort elements in ascending order
sorted_arr = np.sort(data)
print("Sorted: ", sorted_arr)

#find indices where condition is true (values > 2)
cond = np.where(data > 2)
print("Where>2:", cond)

#stack arrays vertically (row-wise)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.vstack((arr1, arr2))
print("Vertical Stack: \n", stacked_arr)

#stack array horizontally (column wise)
stacked_arr = np.hstack((arr1, arr2))
print("Horizontal Stack: \n", stacked_arr)

#make a deep copy array (changes won't affect original)
copy = np.copy(data)



Unquie:  [1 2 3 5]
Sorted:  [1 2 2 3 5]
Where>2: (array([0, 4]),)
Vertical Stack: 
 [[1 2 3]
 [4 5 6]]
Horizontal Stack: 
 [1 2 3 4 5 6]


In [ ]:
#broadcasting
arr = np.array([[1, 2], [3, 4]])
scalar = 10

#add scalar to every element (broadcating)
print("\nBroadcasted Add: \n", arr + scalar)


Broadcasted Add: 
 [[11 12]
 [13 14]]


In [ ]:
#linear algebra
matrix = np.array([[1, 2], [3, 4]])
print("\nMatrix: \n", matrix)

#matrix multiplication(dot product)
dot_product = np.dot(matrix, matrix)
print("\nDot product: \n", dot_product)

#matrix inverse
inverse = np.linalg.inv(matrix)
print("\nInverse: \n", inverse)

#determinant of matrix(useful in solving equation)
print("\nDeterminant: \n", np.linalg.det(matrix))

#eigen values and eigen vectors ( used in ML and PCA)
eigvals, eigvecs = np.linalg.eig(matrix)
print("\nEigen values: ", eigvals)
print("\nEigen vectors: \n", eigvecs)


Matrix: 
 [[1 2]
 [3 4]]

Dot product: 
 [[ 7 10]
 [15 22]]

Inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant: 
 -2.0000000000000004

Eigen values:  [-0.37228132  5.37228132]

Eigen vectors: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
#random module

#fix seed to get the same result every time
np.random.seed(42)

#generate 3*2 array of random values between 0 and 1
rand_arr = np.random.rand(3, 2)
print("\Random[0, 1]: \n", rand_arr)

#generate 10 random values between 0 and 1
rand_arr_2 = np.random.random(10,)
print("\nRandom: \n", rand_arr_2)

#generate 3 random integers between 0 and 9
rand_int = np.random.randint(0, 10, (3,))
print("\nRandom Integers: ", rand_int)





\Random[0, 1]: 
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]

Random: 
 [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451]

Random Integers:  [9 5 8]


In [ ]:
#handling missing values
arr_nan = np.array([1, np.nan, 3, np.nan])

#find positions of NaN values
print("\nNaN positions: ", np.isnan(arr_nan))

#replace NaN values with custom value (e.g 4)
cleaned = np.nan_to_num(arr_nan, nan=4)
print("\nCleaned: ", cleaned)





NaN positions:  [False  True False  True]

Cleaned:  [1. 4. 3. 4.]
